### PR TITLE
NotFound page styled using functional component

### PR DESCRIPTION
**Pull request by JohnnyOhms**
### Worked on issue #27 and Created a styled functional component , with a link to redirect user back to Home page.

**Screenshot before**
JU CollegeWindow - Google Chrome 12_22_2022 12_30_32 PM

**Screenshot After**
JU CollegeWindow - Google Chrome 12_22_2022 12_24_36 PM

**Brach up till Date with master**
**@Ayushpanditmoto Please review and merge, am open for correction**

### CODE REVIEW

**Comment by JohnnyOhms** [comment]
@Ayushpanditmoto i dont understand what you mean, pls explain what i should do by importing the package

**Comment by Ayushpanditmoto** [comment]
Deployment failed because u have not imported styled and Link from react router dom

**Comment by JohnnyOhms** [comment]
Ok, thanks working on it

**Comment by JohnnyOhms** [comment]
Packages imported, ready to be merged

**Pull request merged**
