### PR TITLE
Attakhan

### PR DESCRIPTION
**Pull request by DevAttaKhan**

### CODE REVIEW

**Review by Ayushpanditmoto — COMMENTED** [review]
Its seems good

**Comment by DevAttaKhan** [comment]
Happy to help

**Comment by Ayushpanditmoto** [comment]
@DevAttaKhan  you have done a good works , can you please create a another pull request with up to date branch seems like i got merge conflict.

**Comment by Ayushpanditmoto** [comment]
@DevAttaKhan  

git pull origin master

solve the merge conflict and again raise pull request

**Pull request merged**
